#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/nemo

PRODUCT_COPY_FILES += \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_device/audio_device.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_device/audio_device.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_device/common/audio_device.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_device/common/audio_device.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/AudioParamOptions.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/BtInfo_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/HpImpedance_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/MicInfo_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackACF_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_ParamTreeView.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordDMNR_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordFIR_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVolUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVol_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_ParamTreeView.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVol_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SmartPa_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVol_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_ParamTreeView.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBCall_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBDevice_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VOW_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VOW_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VOW_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VOW_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVol_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_ParamTreeView.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2General_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Volume_AudioParam.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Volume_ParamUnitDesc.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/aurisys_config/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/aurisys_config.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/aurisys_config_hifi3/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config_hifi3/aurisys_config_hifi3.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/awinic/AW_DSP.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/awinic/AW_DSP.bin \
    vendor/realme/nemo/proprietary/odm/etc/audio/oplus_audio_features.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/oplus_audio_features.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/sixth/sixth_param.txt:$(TARGET_COPY_OUT_ODM)/etc/audio/sixth/sixth_param.txt \
    vendor/realme/nemo/proprietary/odm/etc/audio/sixth/sixth_param_app3.txt:$(TARGET_COPY_OUT_ODM)/etc/audio/sixth/sixth_param_app3.txt \
    vendor/realme/nemo/proprietary/odm/etc/audio/sixth/sixth_param_phonecall.txt:$(TARGET_COPY_OUT_ODM)/etc/audio/sixth/sixth_param_phonecall.txt \
    vendor/realme/nemo/proprietary/odm/etc/audio/sixth/sixth_param_voip.txt:$(TARGET_COPY_OUT_ODM)/etc/audio/sixth/sixth_param_voip.txt \
    vendor/realme/nemo/proprietary/odm/etc/audio/test_path/common/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/test_path/common/mixer_paths.xml \
    vendor/realme/nemo/proprietary/odm/etc/audio/test_path/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/test_path/mixer_paths.xml \
    vendor/realme/nemo/proprietary/odm/etc/init/init.pn8x.nfc.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.pn8x.nfc.rc \
    vendor/realme/nemo/proprietary/odm/etc/init/init.pn8x.se.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.pn8x.se.rc \
    vendor/realme/nemo/proprietary/odm/etc/init/vendor.oplus.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/realme/nemo/proprietary/odm/etc/libnfc-nxp-pnscr.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc-nxp-pnscr.conf \
    vendor/realme/nemo/proprietary/odm/firmware/aw87339/aw87339_abrcv.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87339/aw87339_abrcv.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87339/aw87339_drcv.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87339/aw87339_drcv.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87339/aw87339_kspk.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87339/aw87339_kspk.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87339/aw87339_rcvspk.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87339/aw87339_rcvspk.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87339/aw87339_voicespk.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87339/aw87339_voicespk.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87359/aw87359_abrcv.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87359/aw87359_abrcv.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87359/aw87359_abspk.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87359/aw87359_abspk.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87359/aw87359_drcv.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87359/aw87359_drcv.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87359/aw87359_dspk.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87359/aw87359_dspk.bin \
    vendor/realme/nemo/proprietary/odm/firmware/aw87359/aw87359_dspk_ftm.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw87359/aw87359_dspk_ftm.bin \
    vendor/realme/nemo/proprietary/odm/firmware/fastchg/19661/oplus_vooc_fw.bin:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/19661/oplus_vooc_fw.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/FW_NT36672C_NF_JDI.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/FW_NT36672C_NF_JDI.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/FW_NT36672C_NF_JDI_FAE.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/FW_NT36672C_NF_JDI_FAE.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/FW_NT36672C_NF_JDI_TEST.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/FW_NT36672C_NF_JDI_TEST.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/FW_NT36672C_NF_TIANMA.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/FW_NT36672C_NF_TIANMA.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/FW_NT36672C_NF_TIANMA_FAE.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/FW_NT36672C_NF_TIANMA_FAE.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/FW_NT36672C_NF_TIANMA_TEST.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/FW_NT36672C_NF_TIANMA_TEST.bin \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/LIMIT_NT36672C_NF_JDI.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/LIMIT_NT36672C_NF_JDI.img \
    vendor/realme/nemo/proprietary/odm/firmware/tp/19661/LIMIT_NT36672C_NF_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/19661/LIMIT_NT36672C_NF_TIANMA.img \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/030b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/030b0000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/030b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/030b0000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/04010000000000000000000000000007.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/04010000000000000000000000000007.tlbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/04320000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/04320000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/070f0000000000000000000000000a0a.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/070f0000000000000000000000000a0a.tlbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/08010203000000000000000000000000.tabin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/08010203000000000000000000000000.tabin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/09070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/09070000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/09080000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/09080000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/odm/vendor/app/mcRegistry/09150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/09150000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07060000000000000000000000007169.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000007169.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07060000000000000000000000007169.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000007169.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08020000000000000000000000007169.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08020000000000000000000000007169.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08070000000000000000000000008270.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08070000000000000000000000008270.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08070000000000000000000000008270.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08070000000000000000000000008270.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/09010000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09010000000000000000000000000000.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/09030000000000000000000000008270.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09030000000000000000000000008270.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/09190000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09190000000000000000000000000000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/realme/nemo/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/realme/nemo/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/realme/nemo/proprietary/vendor/etc/.tp/.thermal_policy_08:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_08 \
    vendor/realme/nemo/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/realme/nemo/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/realme/nemo/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/realme/nemo/proprietary/vendor/etc/apdb/APDB_MT6785_S01__W2044:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6785_S01__W2044 \
    vendor/realme/nemo/proprietary/vendor/etc/apdb/APDB_MT6785_S01__W2044_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6785_S01__W2044_ENUM \
    vendor/realme/nemo/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/realme/nemo/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/realme/nemo/proprietary/vendor/etc/audio_em.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_em.xml \
    vendor/realme/nemo/proprietary/vendor/etc/audio_policy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy.conf \
    vendor/realme/nemo/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/realme/nemo/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/realme/nemo/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/realme/nemo/proprietary/vendor/etc/default_pd_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/etc/default_pd_calibration.bin \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/realme/nemo/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_QXWZ.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_QXWZ.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/realme/nemo/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Vodafone.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Vodafone.xml \
    vendor/realme/nemo/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-mediatek.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service.trustonic.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/bootperf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bootperf.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/em_hidl_user.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/em_hidl_user.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.cccifsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccifsd.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/init.xcap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.xcap.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/md_monitor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/md_monitor.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/networksetting.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/networksetting.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/ppl_agent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ppl_agent.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.dfps@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.dfps@1.0-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.gpu@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.gpu@1.0-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.keyinstall@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keyinstall@1.0-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.5-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.5-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkcodecservice@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkcodecservice@1.1-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/realme/nemo/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.conf \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root-R3.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root-R3.cer \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/gold.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/gold.cer \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/thawte.der \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ssl/openssl.cnf \
    vendor/realme/nemo/proprietary/vendor/etc/ipsec/strongswan.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/strongswan.conf \
    vendor/realme/nemo/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/realme/nemo/proprietary/vendor/etc/media_codecs_mediatek_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_audio.xml \
    vendor/realme/nemo/proprietary/vendor/etc/media_codecs_mediatek_video.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_video.xml \
    vendor/realme/nemo/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/realme/nemo/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/realme/nemo/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/realme/nemo/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/realme/nemo/proprietary/vendor/etc/nhw:$(TARGET_COPY_OUT_VENDOR)/etc/nhw \
    vendor/realme/nemo/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/realme/nemo/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/realme/nemo/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/realme/nemo/proprietary/vendor/etc/seccomp_policy/mediaswcodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaswcodec.policy \
    vendor/realme/nemo/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/realme/nemo/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/realme/nemo/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/realme/nemo/proprietary/vendor/etc/spn-conf-op09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/spn-conf-op09.xml \
    vendor/realme/nemo/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/realme/nemo/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/realme/nemo/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/realme/nemo/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/realme/nemo/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/realme/nemo/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/realme/nemo/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/realme/nemo/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/realme/nemo/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_2a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_2a_1.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/realme/nemo/proprietary/vendor/firmware/catcher_filter_1_ulwctg_n.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/catcher_filter_1_ulwctg_n.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/customfilter/catcher_filter_1_ulwctg_n_FullLog.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_FullLog.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/customfilter/catcher_filter_1_ulwctg_n_PLS_PS_ONLY.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_PLS_PS_ONLY.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/customfilter/catcher_filter_1_ulwctg_n_SlimLog_DspAllOff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_SlimLog_DspAllOff.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/customfilter/catcher_filter_1_ulwctg_n__Default.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n__Default.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/customfilter/catcher_filter_1_ulwctg_n_meta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_meta.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/em_filter_1_ulwctg_n.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/em_filter_1_ulwctg_n.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/realme/nemo/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/soc1_0_patch_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_2a_1_hdr.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/soc1_0_ram_bt_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_2a_1_hdr.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/soc1_0_ram_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_2a_1_hdr.bin \
    vendor/realme/nemo/proprietary/vendor/firmware/soc1_0_ram_wifi_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_2a_1_hdr.bin \
    vendor/realme/nemo/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    libaptXHD_encoder \
    libaptX_encoder \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_trace \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gps.default \
    vendor.mediatek.hardware.keyinstall@1.0-impl \
    vendor.mediatek.hardware.mms@1.5-impl \
    vendor.mediatek.hardware.pq@2.6-impl \
    libJpgEncPipe \
    libOpenCL \
    libTEECommon \
    libaal_mtk \
    libaalservice \
    libbwc \
    libcapctrl \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcharon-ss \
    libcrypto-md \
    libcrypto-ss \
    libcurl-md \
    libcurl-ss \
    libcustom_nvram \
    libdpframework \
    libfile_op \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libhdrvideo \
    libhwm \
    libhydra \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libmtcloader \
    libmtk_drvb \
    libmtkares \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtksysutils \
    libnvram \
    libnvram_daemon_callback \
    libnvram_platform \
    libnvram_sec \
    libpixelflinger \
    libpq_cust_base \
    libpq_prot \
    librgbwlightsensor \
    libscltm \
    libsimaka \
    libssl-md \
    libssl-ss \
    libstrongswan \
    libsysenv \
    liburee_meta_drmkeyinstall \
    libverno \
    libvpu \
    libwo \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.gpu@1.0 \
    vendor.mediatek.hardware.keyinstall@1.0 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    AVCSecureVdecCA \
    VP9SecureVdecCA \
    audio.primary.mt6785 \
    sound_trigger.primary.mt6785 \
    vendor.mediatek.hardware.mtkcodecservice@1.1-impl \
    libDR \
    libHEVCdec_sa.ca7.android \
    libMtkOmxAdpcmDec \
    libMtkOmxAlacDec \
    libMtkOmxApeDec \
    libMtkOmxCore \
    libMtkOmxGsmDec \
    libMtkOmxMp3Dec \
    libMtkOmxVdecEx \
    libMtkOmxVenc \
    libMtkOmxWmaDec \
    libMtkSpeechEnh \
    lib_iir \
    lib_speech_enh \
    libalsautils-v30 \
    libaudio_engineer_test \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcvsd_mtk \
    libfgauge_gm30 \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libhevce_sb.ca7.android \
    libktvdrc \
    libktveffect \
    libktveffect_rec \
    libktveq \
    libktvns \
    libktvreverb \
    libktvsoundtouch \
    libktvvolume \
    libmnl \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    libmsbc_mtk \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    liboplus_audio_config \
    libsi_sixth \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstagefrighthw \
    libstorage_otp \
    libthermalalgo \
    libthha \
    libvc1dec_sa.ca7 \
    libvcodec_oal \
    libvcodec_utility \
    libvcodecdrv \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvow_ap_testing_alexa.vendor \
    libvowp23_sid_testing_alexa.vendor \
    libvowp23_sid_training_alexa.vendor \
    libvowp25testing_alexa.vendor \
    libvowp2training_alexa.vendor \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    libvt_custom \
    vendor.mediatek.hardware.mtkcodecservice@1.1 \
    APUWareUtilsServer \
    APUWareXrpServer \
    gc02k0_mipi_raw_IdxMgr \
    gc02k0_mipi_raw_tuning \
    gc02m0_mipi_mono_IdxMgr \
    gc02m0_mipi_mono_tuning \
    gc2375h_mipi_raw_19661_IdxMgr \
    gc2375h_mipi_raw_19661_tuning \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    dfps.mt6785 \
    hwcomposer.mt6785 \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    sensors.mt6785 \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.camera.postproc@1.0-impl \
    vendor.mediatek.hardware.dfps@1.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    imx471_mipi_raw1_IdxMgr \
    imx471_mipi_raw1_tuning \
    imx682_mipi_raw_IdxMgr \
    imx682_mipi_raw_tuning \
    lbs_hidl_service-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.core \
    lib3a.af \
    lib3a.awb.core \
    lib3a.awb \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.flash \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    libCamera_gc02k0mipiraw_Reserved \
    libCamera_gc02k0mipiraw_Scene_Capture \
    libCamera_gc02k0mipiraw_Scene_Preview \
    libCamera_gc02m0mipimono_Capture_Preview \
    libCamera_gc02m0mipimono_Default_Video \
    libCamera_gc02m0mipimono_Production_Capture \
    libCamera_gc02m0mipimono_Reserved \
    libCamera_gc02m0mipimono_Scene_Capture \
    libCamera_gc2375hmipiraw19661_Reserved \
    libCamera_gc2375hmipiraw19661_Scene_Capture \
    libCamera_gc2375hmipiraw19661_Scene_Preview \
    libCamera_imx471mipiraw1_3HDR_Preivew \
    libCamera_imx471mipiraw1_3rd_Capture_1080P \
    libCamera_imx471mipiraw1_3rd_Capture_480P \
    libCamera_imx471mipiraw1_3rd_Capture_720P \
    libCamera_imx471mipiraw1_3rd_Preview_1080P \
    libCamera_imx471mipiraw1_3rd_Preview_480P \
    libCamera_imx471mipiraw1_3rd_Preview_720P \
    libCamera_imx471mipiraw1_FaceBeauty_Capture \
    libCamera_imx471mipiraw1_FaceBeauty_Capture_Bining \
    libCamera_imx471mipiraw1_FaceBeauty_Preview_Noface \
    libCamera_imx471mipiraw1_FaceBeauty_Scene_Preview \
    libCamera_imx471mipiraw1_FaceUnlock \
    libCamera_imx471mipiraw1_Face_Capture \
    libCamera_imx471mipiraw1_Face_Capture_superNS \
    libCamera_imx471mipiraw1_Flash_Capture \
    libCamera_imx471mipiraw1_Panorama \
    libCamera_imx471mipiraw1_Production_Capture \
    libCamera_imx471mipiraw1_Reserved \
    libCamera_imx471mipiraw1_Scene_Capture \
    libCamera_imx471mipiraw1_Scene_Capture_Bining \
    libCamera_imx471mipiraw1_Scene_Preview \
    libCamera_imx471mipiraw1_SlowMotion_Video \
    libCamera_imx471mipiraw1_Video_Recording \
    libCamera_imx471mipiraw1_WeChatQQ_1080P \
    libCamera_imx471mipiraw1_WeChatQQ_480P \
    libCamera_imx471mipiraw1_WeChatQQ_720P \
    libCamera_imx471mipiraw1_YUVHDR_Capture \
    libCamera_imx471mipiraw1_YUVHDR_Capture_Binning \
    libCamera_imx471mipiraw1_subject_capture \
    libCamera_imx471mipiraw1_zHDR_Capture_Binning \
    libCamera_imx682mipiraw_3rd_Capture \
    libCamera_imx682mipiraw_3rd_Capture2 \
    libCamera_imx682mipiraw_EIS_Video4K \
    libCamera_imx682mipiraw_Face_Capture \
    libCamera_imx682mipiraw_Face_Capture_64 \
    libCamera_imx682mipiraw_Face_Preview \
    libCamera_imx682mipiraw_Flash_Capture \
    libCamera_imx682mipiraw_Flash_Preview_PF \
    libCamera_imx682mipiraw_HDR_Scene_Capture \
    libCamera_imx682mipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_imx682mipiraw_MFSR_Scene_Capture_Zoom2 \
    libCamera_imx682mipiraw_Panorama_Capture \
    libCamera_imx682mipiraw_Professional_capture \
    libCamera_imx682mipiraw_QQ_Capture_ChatMode \
    libCamera_imx682mipiraw_Reserved \
    libCamera_imx682mipiraw_Scene_Capture \
    libCamera_imx682mipiraw_Scene_Capture_64 \
    libCamera_imx682mipiraw_Scene_Preview \
    libCamera_imx682mipiraw_Scene_Preview_Zoom1 \
    libCamera_imx682mipiraw_Scene_Preview_Zoom2 \
    libCamera_imx682mipiraw_SuperNS_Face_Preview \
    libCamera_imx682mipiraw_SuperNS_Scene_Capture \
    libCamera_imx682mipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_imx682mipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_imx682mipiraw_SuperNS_Scene_Preview \
    libCamera_imx682mipiraw_Torch_Capture \
    libCamera_imx682mipiraw_Video \
    libCamera_imx682mipiraw_Video_1080P_60fps \
    libCamera_imx682mipiraw_Video_1080P_EIS \
    libCamera_imx682mipiraw_Video_30fps \
    libCamera_imx682mipiraw_Video_480P \
    libCamera_imx682mipiraw_Video_4K \
    libCamera_imx682mipiraw_Video_4K_Zoom1 \
    libCamera_imx682mipiraw_Video_4K_Zoom2 \
    libCamera_imx682mipiraw_Video_60fps \
    libCamera_imx682mipiraw_Video_720P \
    libCamera_imx682mipiraw_Video_720P_1080P_120fps \
    libCamera_imx682mipiraw_Video_720P_240fps \
    libCamera_imx682mipiraw_Video_720P_EIS \
    libCamera_imx682mipiraw_Video_EIS_Default \
    libCamera_imx682mipiraw_Video_Zoom1 \
    libCamera_imx682mipiraw_Video_Zoom2 \
    libCamera_imx682mipiraw_Video_zoom \
    libCamera_imx682mipiraw_Zoom_capture \
    libCamera_imx682mipiraw_portrait_capture_full \
    libCamera_imx682mipiraw_portrait_preview_full \
    libCamera_ov02b10mipiraw_Reserved \
    libCamera_ov02b10mipiraw_Scene_Capture \
    libCamera_ov02b10mipiraw_Scene_Preview \
    libCamera_ov02b1bmipimono_Capture_Preview \
    libCamera_ov02b1bmipimono_Default_Video \
    libCamera_ov02b1bmipimono_Production_Capture \
    libCamera_ov02b1bmipimono_Reserved \
    libCamera_ov02b1bmipimono_Scene_Capture \
    libCamera_ov8856mipiraw_AutoHDR_Capture \
    libCamera_ov8856mipiraw_AutoHDR_Preview \
    libCamera_ov8856mipiraw_AutoHDR_Video \
    libCamera_ov8856mipiraw_Face_Capture \
    libCamera_ov8856mipiraw_Face_Capture_superNS \
    libCamera_ov8856mipiraw_Flash_Capture \
    libCamera_ov8856mipiraw_Flash_HDR_Capture \
    libCamera_ov8856mipiraw_HDR_Capture \
    libCamera_ov8856mipiraw_HDR_Preview \
    libCamera_ov8856mipiraw_HDR_Video \
    libCamera_ov8856mipiraw_N3D_Capture \
    libCamera_ov8856mipiraw_N3D_Capture_48M \
    libCamera_ov8856mipiraw_N3D_Preview \
    libCamera_ov8856mipiraw_N3D_Preview_48M \
    libCamera_ov8856mipiraw_N3D_Video \
    libCamera_ov8856mipiraw_Reserved \
    libCamera_ov8856mipiraw_Scene_Capture \
    libCamera_ov8856mipiraw_Scene_Capture_4cell \
    libCamera_ov8856mipiraw_Scene_Capture_superNS \
    libCamera_ov8856mipiraw_Scene_Preview \
    libCamera_ov8856mipiraw_Scene_Preview_4k \
    libCamera_ov8856mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_ov8856mipiraw_Scene_Preview_ZSD_superNS \
    libCamera_ov8856mipiraw_Video_1080 \
    libCamera_ov8856mipiraw_Video_4k \
    libCamera_s5k3p9spmipiraw_3HDR_Preivew \
    libCamera_s5k3p9spmipiraw_3rd_Capture_1080P \
    libCamera_s5k3p9spmipiraw_3rd_Capture_480P \
    libCamera_s5k3p9spmipiraw_3rd_Capture_720P \
    libCamera_s5k3p9spmipiraw_3rd_Preview_1080P \
    libCamera_s5k3p9spmipiraw_3rd_Preview_480P \
    libCamera_s5k3p9spmipiraw_3rd_Preview_720P \
    libCamera_s5k3p9spmipiraw_FaceBeauty_Capture \
    libCamera_s5k3p9spmipiraw_FaceBeauty_Capture_Bining \
    libCamera_s5k3p9spmipiraw_FaceBeauty_Preview_Noface \
    libCamera_s5k3p9spmipiraw_FaceBeauty_Scene_Preview \
    libCamera_s5k3p9spmipiraw_FaceUnlock \
    libCamera_s5k3p9spmipiraw_Face_Capture \
    libCamera_s5k3p9spmipiraw_Face_Capture_superNS \
    libCamera_s5k3p9spmipiraw_Flash_Capture \
    libCamera_s5k3p9spmipiraw_Panorama \
    libCamera_s5k3p9spmipiraw_Production_Capture \
    libCamera_s5k3p9spmipiraw_Reserved \
    libCamera_s5k3p9spmipiraw_Scene_Capture \
    libCamera_s5k3p9spmipiraw_Scene_Capture_Bining \
    libCamera_s5k3p9spmipiraw_Scene_Preview \
    libCamera_s5k3p9spmipiraw_SlowMotion_Video \
    libCamera_s5k3p9spmipiraw_Video_Recording \
    libCamera_s5k3p9spmipiraw_WeChatQQ_1080P \
    libCamera_s5k3p9spmipiraw_WeChatQQ_480P \
    libCamera_s5k3p9spmipiraw_WeChatQQ_720P \
    libCamera_s5k3p9spmipiraw_YUVHDR_Capture \
    libCamera_s5k3p9spmipiraw_YUVHDR_Capture_Binning \
    libCamera_s5k3p9spmipiraw_zHDR_Capture_Binning \
    libCamera_s5kgm1spmipiraw_EIS_Video4K \
    libCamera_s5kgm1spmipiraw_Face_Capture \
    libCamera_s5kgm1spmipiraw_Face_Capture_64 \
    libCamera_s5kgm1spmipiraw_Face_Preview \
    libCamera_s5kgm1spmipiraw_Flash_Capture \
    libCamera_s5kgm1spmipiraw_Flash_Preview_PF \
    libCamera_s5kgm1spmipiraw_HDR_Scene_Capture \
    libCamera_s5kgm1spmipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kgm1spmipiraw_MFSR_Scene_Capture_Zoom2 \
    libCamera_s5kgm1spmipiraw_Panorama_Capture \
    libCamera_s5kgm1spmipiraw_Professional_capture \
    libCamera_s5kgm1spmipiraw_QQ_Capture_ChatMode \
    libCamera_s5kgm1spmipiraw_QQ_Preview \
    libCamera_s5kgm1spmipiraw_Reserved \
    libCamera_s5kgm1spmipiraw_Scene_Capture \
    libCamera_s5kgm1spmipiraw_Scene_Capture_64 \
    libCamera_s5kgm1spmipiraw_Scene_Preview \
    libCamera_s5kgm1spmipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kgm1spmipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kgm1spmipiraw_SuperNS_Face_Preview \
    libCamera_s5kgm1spmipiraw_SuperNS_Scene_Capture \
    libCamera_s5kgm1spmipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kgm1spmipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kgm1spmipiraw_SuperNS_Scene_Preview \
    libCamera_s5kgm1spmipiraw_Torch_Capture \
    libCamera_s5kgm1spmipiraw_Video \
    libCamera_s5kgm1spmipiraw_Video_1080P_60fps \
    libCamera_s5kgm1spmipiraw_Video_1080P_EIS \
    libCamera_s5kgm1spmipiraw_Video_30fps \
    libCamera_s5kgm1spmipiraw_Video_480P \
    libCamera_s5kgm1spmipiraw_Video_4K \
    libCamera_s5kgm1spmipiraw_Video_4K_Zoom1 \
    libCamera_s5kgm1spmipiraw_Video_60fps \
    libCamera_s5kgm1spmipiraw_Video_720P \
    libCamera_s5kgm1spmipiraw_Video_720P_1080P_120fps \
    libCamera_s5kgm1spmipiraw_Video_720P_240fps \
    libCamera_s5kgm1spmipiraw_Video_720P_EIS \
    libCamera_s5kgm1spmipiraw_Video_EIS_Default \
    libCamera_s5kgm1spmipiraw_Video_Zoom1 \
    libCamera_s5kgm1spmipiraw_Video_Zoom2 \
    libCamera_s5kgm1spmipiraw_Video_zoom \
    libCamera_s5kgm1spmipiraw_Zoom_capture \
    libCamera_s5kgm1spmipiraw_portrait_capture_full \
    libCamera_s5kgm1spmipiraw_portrait_preview_full \
    libCamera_s5kgw1mipiraw_EIS_Video4K \
    libCamera_s5kgw1mipiraw_Face_Capture \
    libCamera_s5kgw1mipiraw_Face_Capture_64 \
    libCamera_s5kgw1mipiraw_Face_Preview \
    libCamera_s5kgw1mipiraw_Flash_Capture \
    libCamera_s5kgw1mipiraw_Flash_Preview_PF \
    libCamera_s5kgw1mipiraw_HDR_Scene_Capture \
    libCamera_s5kgw1mipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kgw1mipiraw_MFSR_Scene_Capture_Zoom2 \
    libCamera_s5kgw1mipiraw_Panorama_Capture \
    libCamera_s5kgw1mipiraw_Professional_capture \
    libCamera_s5kgw1mipiraw_QQ_Capture_ChatMode \
    libCamera_s5kgw1mipiraw_Reserved \
    libCamera_s5kgw1mipiraw_Scene_Capture \
    libCamera_s5kgw1mipiraw_Scene_Capture_64 \
    libCamera_s5kgw1mipiraw_Scene_Preview \
    libCamera_s5kgw1mipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kgw1mipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kgw1mipiraw_SuperNS_Face_Preview \
    libCamera_s5kgw1mipiraw_SuperNS_Scene_Capture \
    libCamera_s5kgw1mipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kgw1mipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kgw1mipiraw_SuperNS_Scene_Preview \
    libCamera_s5kgw1mipiraw_Torch_Capture \
    libCamera_s5kgw1mipiraw_Video \
    libCamera_s5kgw1mipiraw_Video_1080P_60fps \
    libCamera_s5kgw1mipiraw_Video_1080P_EIS \
    libCamera_s5kgw1mipiraw_Video_30fps \
    libCamera_s5kgw1mipiraw_Video_480P \
    libCamera_s5kgw1mipiraw_Video_4K \
    libCamera_s5kgw1mipiraw_Video_4K_Zoom1 \
    libCamera_s5kgw1mipiraw_Video_4K_Zoom2 \
    libCamera_s5kgw1mipiraw_Video_60fps \
    libCamera_s5kgw1mipiraw_Video_720P \
    libCamera_s5kgw1mipiraw_Video_720P_1080P_120fps \
    libCamera_s5kgw1mipiraw_Video_720P_240fps \
    libCamera_s5kgw1mipiraw_Video_720P_EIS \
    libCamera_s5kgw1mipiraw_Video_EIS_Default \
    libCamera_s5kgw1mipiraw_Video_Zoom1 \
    libCamera_s5kgw1mipiraw_Video_Zoom2 \
    libCamera_s5kgw1mipiraw_Video_zoom \
    libCamera_s5kgw1mipiraw_Zoom_capture \
    libCamera_s5kgw1mipiraw_portrait_capture_full \
    libCamera_s5kgw1mipiraw_portrait_preview_full \
    libCamera_salaaqtechmains5kgm1sp_EIS_Video4K \
    libCamera_salaaqtechmains5kgm1sp_Face_Capture \
    libCamera_salaaqtechmains5kgm1sp_Face_Capture_64 \
    libCamera_salaaqtechmains5kgm1sp_Face_Preview \
    libCamera_salaaqtechmains5kgm1sp_Flash_Capture \
    libCamera_salaaqtechmains5kgm1sp_Flash_Preview_PF \
    libCamera_salaaqtechmains5kgm1sp_HDR_Scene_Capture \
    libCamera_salaaqtechmains5kgm1sp_MFSR_Scene_Capture_Zoom1 \
    libCamera_salaaqtechmains5kgm1sp_MFSR_Scene_Capture_Zoom2 \
    libCamera_salaaqtechmains5kgm1sp_Panorama_Capture \
    libCamera_salaaqtechmains5kgm1sp_Professional_capture \
    libCamera_salaaqtechmains5kgm1sp_QQ_Capture_ChatMode \
    libCamera_salaaqtechmains5kgm1sp_QQ_Preview \
    libCamera_salaaqtechmains5kgm1sp_Reserved \
    libCamera_salaaqtechmains5kgm1sp_Scene_Capture \
    libCamera_salaaqtechmains5kgm1sp_Scene_Capture_64 \
    libCamera_salaaqtechmains5kgm1sp_Scene_Preview \
    libCamera_salaaqtechmains5kgm1sp_Scene_Preview_Zoom1 \
    libCamera_salaaqtechmains5kgm1sp_Scene_Preview_Zoom2 \
    libCamera_salaaqtechmains5kgm1sp_SuperNS_Face_Preview \
    libCamera_salaaqtechmains5kgm1sp_SuperNS_Scene_Capture \
    libCamera_salaaqtechmains5kgm1sp_SuperNS_Scene_Capture_Zoom1 \
    libCamera_salaaqtechmains5kgm1sp_SuperNS_Scene_Capture_Zoom2 \
    libCamera_salaaqtechmains5kgm1sp_SuperNS_Scene_Preview \
    libCamera_salaaqtechmains5kgm1sp_Torch_Capture \
    libCamera_salaaqtechmains5kgm1sp_Video \
    libCamera_salaaqtechmains5kgm1sp_Video_1080P_60fps \
    libCamera_salaaqtechmains5kgm1sp_Video_1080P_EIS \
    libCamera_salaaqtechmains5kgm1sp_Video_30fps \
    libCamera_salaaqtechmains5kgm1sp_Video_480P \
    libCamera_salaaqtechmains5kgm1sp_Video_4K \
    libCamera_salaaqtechmains5kgm1sp_Video_4K_Zoom1 \
    libCamera_salaaqtechmains5kgm1sp_Video_60fps \
    libCamera_salaaqtechmains5kgm1sp_Video_720P \
    libCamera_salaaqtechmains5kgm1sp_Video_720P_1080P_120fps \
    libCamera_salaaqtechmains5kgm1sp_Video_720P_240fps \
    libCamera_salaaqtechmains5kgm1sp_Video_720P_EIS \
    libCamera_salaaqtechmains5kgm1sp_Video_EIS_Default \
    libCamera_salaaqtechmains5kgm1sp_Video_Zoom1 \
    libCamera_salaaqtechmains5kgm1sp_Video_Zoom2 \
    libCamera_salaaqtechmains5kgm1sp_Video_zoom \
    libCamera_salaaqtechmains5kgm1sp_Zoom_capture \
    libCamera_salaaqtechmains5kgm1sp_portrait_capture_full \
    libCamera_salaaqtechmains5kgm1sp_portrait_preview_full \
    libCamera_salawideov8856_AutoHDR_Capture \
    libCamera_salawideov8856_AutoHDR_Preview \
    libCamera_salawideov8856_AutoHDR_Video \
    libCamera_salawideov8856_Face_Capture \
    libCamera_salawideov8856_Face_Capture_superNS \
    libCamera_salawideov8856_Flash_Capture \
    libCamera_salawideov8856_Flash_HDR_Capture \
    libCamera_salawideov8856_HDR_Capture \
    libCamera_salawideov8856_HDR_Preview \
    libCamera_salawideov8856_HDR_Video \
    libCamera_salawideov8856_N3D_Capture \
    libCamera_salawideov8856_N3D_Capture_48M \
    libCamera_salawideov8856_N3D_Preview \
    libCamera_salawideov8856_N3D_Preview_48M \
    libCamera_salawideov8856_N3D_Video \
    libCamera_salawideov8856_Reserved \
    libCamera_salawideov8856_Scene_Capture \
    libCamera_salawideov8856_Scene_Capture_4cell \
    libCamera_salawideov8856_Scene_Capture_superNS \
    libCamera_salawideov8856_Scene_Preview \
    libCamera_salawideov8856_Scene_Preview_4k \
    libCamera_salawideov8856_Scene_Preview_ZSD_Flash \
    libCamera_salawideov8856_Scene_Preview_ZSD_superNS \
    libCamera_salawideov8856_Video_1080 \
    libCamera_salawideov8856_Video_4k \
    libCamera_sarterqtechmains5kgm1sp_EIS_Video4K \
    libCamera_sarterqtechmains5kgm1sp_Face_Capture \
    libCamera_sarterqtechmains5kgm1sp_Face_Capture_64 \
    libCamera_sarterqtechmains5kgm1sp_Face_Preview \
    libCamera_sarterqtechmains5kgm1sp_Flash_Capture \
    libCamera_sarterqtechmains5kgm1sp_Flash_Preview_PF \
    libCamera_sarterqtechmains5kgm1sp_HDR_Scene_Capture \
    libCamera_sarterqtechmains5kgm1sp_MFSR_Scene_Capture_Zoom1 \
    libCamera_sarterqtechmains5kgm1sp_MFSR_Scene_Capture_Zoom2 \
    libCamera_sarterqtechmains5kgm1sp_Panorama_Capture \
    libCamera_sarterqtechmains5kgm1sp_Professional_capture \
    libCamera_sarterqtechmains5kgm1sp_QQ_Capture_ChatMode \
    libCamera_sarterqtechmains5kgm1sp_Reserved \
    libCamera_sarterqtechmains5kgm1sp_Scene_Capture \
    libCamera_sarterqtechmains5kgm1sp_Scene_Capture_64 \
    libCamera_sarterqtechmains5kgm1sp_Scene_Preview \
    libCamera_sarterqtechmains5kgm1sp_Scene_Preview_Zoom1 \
    libCamera_sarterqtechmains5kgm1sp_Scene_Preview_Zoom2 \
    libCamera_sarterqtechmains5kgm1sp_SuperNS_Face_Preview \
    libCamera_sarterqtechmains5kgm1sp_SuperNS_Scene_Capture \
    libCamera_sarterqtechmains5kgm1sp_SuperNS_Scene_Capture_Zoom1 \
    libCamera_sarterqtechmains5kgm1sp_SuperNS_Scene_Capture_Zoom2 \
    libCamera_sarterqtechmains5kgm1sp_SuperNS_Scene_Preview \
    libCamera_sarterqtechmains5kgm1sp_Torch_Capture \
    libCamera_sarterqtechmains5kgm1sp_Video \
    libCamera_sarterqtechmains5kgm1sp_Video_1080P_60fps \
    libCamera_sarterqtechmains5kgm1sp_Video_1080P_EIS \
    libCamera_sarterqtechmains5kgm1sp_Video_30fps \
    libCamera_sarterqtechmains5kgm1sp_Video_480P \
    libCamera_sarterqtechmains5kgm1sp_Video_4K \
    libCamera_sarterqtechmains5kgm1sp_Video_4K_Zoom1 \
    libCamera_sarterqtechmains5kgm1sp_Video_4K_Zoom2 \
    libCamera_sarterqtechmains5kgm1sp_Video_60fps \
    libCamera_sarterqtechmains5kgm1sp_Video_720P \
    libCamera_sarterqtechmains5kgm1sp_Video_720P_1080P_120fps \
    libCamera_sarterqtechmains5kgm1sp_Video_720P_240fps \
    libCamera_sarterqtechmains5kgm1sp_Video_720P_EIS \
    libCamera_sarterqtechmains5kgm1sp_Video_EIS_Default \
    libCamera_sarterqtechmains5kgm1sp_Video_Zoom1 \
    libCamera_sarterqtechmains5kgm1sp_Video_Zoom2 \
    libCamera_sarterqtechmains5kgm1sp_Video_zoom \
    libCamera_sarterqtechmains5kgm1sp_Zoom_capture \
    libCamera_sarterqtechmains5kgm1sp_portrait_capture_full \
    libCamera_sarterqtechmains5kgm1sp_portrait_preview_full \
    libFaceBeautyCap \
    libFaceBeautyPre \
    libMcClient \
    libPerfectlyClearCrux \
    libPolarrRender \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libVDBlurless \
    libVDPostureDetection \
    libVDSuperPhotoAPI \
    libWaterMark \
    lib_bsscore \
    libaal_cust \
    libaal_key \
    libakm \
    libapusys \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_bokeh_api \
    libarcsoft_dualcam_refocus_left \
    libarcsoft_dualcam_refocus_preview \
    libarcsoft_dualcam_refocus_right \
    libarcsoft_hdr_couple_api \
    libarcsoft_hdr_denoise_api \
    libarcsoft_high_dynamic_range \
    libarcsoft_high_dynamic_range_couple \
    libarcsoft_lensstaindetection \
    libarcsoft_low_light_hdr \
    libarcsoft_relighting_pro_image \
    libarcsoft_scbokeh_image \
    libarcsoft_smart_denoise \
    libarcsoft_supervideostabilization \
    libarcsoft_videostabilizer \
    libarmnn \
    libarmnn_ndk.mtk \
    libbluetooth_audio_session_mediatek \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3 \
    libcam.halisp \
    libcam.halsensor \
    libcam.iopipe \
    libcam.lcs \
    libcam.pdtblgen \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3a_imem \
    libcamalgo.3dnr \
    libcamalgo.asd \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.flicker \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.utility \
    libcamalgo.vpunr \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_core_hwi \
    libcameracustom.eis \
    libcameracustom \
    libchromanr \
    libcmdl \
    libcmdl_ndk.mtk \
    libcvface_api \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libgz_uree \
    libhwm-oppo \
    libifcutils_mtk \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libmfllcore \
    libml_util \
    libmpbase \
    libmsnr \
    libmtk-ril \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_dpe \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkisp_metadata \
    libmtkrilutils \
    libmtktinyxml \
    libmtkutils \
    libneuroeara \
    libneuron_adapter \
    libneuron_platform \
    libneuron_runtime \
    libneuropilot_hal_utils \
    libneuropilot_jni_R \
    libnir_neon_driver \
    libnir_neon_driver_ndk.mtk \
    libnxprecord \
    libnxpspeech \
    libocam_common \
    liboppo_aisd \
    liboppo_arcSoftBokehEngine_new \
    liboppo_blank_algo \
    liboppo_platform_hwi \
    libratconfig \
    librilfusion \
    libsensor_custom \
    libstereoinfoaccessor_vsdof \
    libstface_fd_api \
    libtflite_mtk \
    libtflite_mtk_static_R \
    libtlcWidevineModularDrm \
    libudf \
    libutils-v30 \
    libwifi-hal-mtk \
    libwifitest \
    libwvhidl \
    libwvdrmengine \
    libmtkcam_streaminfo_plugin-p1stt \
    ov02b10_mipi_raw_IdxMgr \
    ov02b10_mipi_raw_tuning \
    ov02b1b_mipi_mono_IdxMgr \
    ov02b1b_mipi_mono_tuning \
    ov8856_mipi_raw_IdxMgr \
    ov8856_mipi_raw_tuning \
    s5k3p9sp_mipi_raw_IdxMgr \
    s5k3p9sp_mipi_raw_tuning \
    s5kgm1sp_mipi_raw_IdxMgr \
    s5kgm1sp_mipi_raw_tuning \
    s5kgw1_mipi_raw_IdxMgr \
    s5kgw1_mipi_raw_tuning \
    sala_wide_ov8856_IdxMgr \
    sala_wide_ov8856_tuning \
    salaa_qtech_main_s5kgm1sp_IdxMgr \
    salaa_qtech_main_s5kgm1sp_tuning \
    sarter_qtech_main_s5kgm1sp_IdxMgr \
    sarter_qtech_main_s5kgm1sp_tuning \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.camdump@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.dfps@1.0 \
    vendor.mediatek.hardware.engineermode@1.0 \
    vendor.mediatek.hardware.engineermode@1.1 \
    vendor.mediatek.hardware.engineermode@1.2 \
    vendor.mediatek.hardware.engineermode@1.3 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mdmonitor@1.0 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pplagent@1.0 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libem_support_jni \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libsignal \
    libsink-mtk \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    liboemcrypto \
    libormshalclient \
    libpnscr2 \
    sensors.virtual \
    vendor.oplus.hardware.appradio@1.0 \
    vendor.oplus.hardware.biometrics.fingerprint@2.1_odm \
    vendor.oplus.hardware.biometrics.fingerprintservice@1.0 \
    vendor.oplus.hardware.commondcs@1.0 \
    vendor.oplus.hardware.orms@1.0 \
    vendor.oplus.hardware.radio@1.0 \
    ImsService \
    EngineerMode \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-ims-legacy \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    android.hardware.gpu@1.0-service.xml \
    android.hardware.neuralnetworks@1.3-service-mtk-dsp-gpu.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    oplus_appradio_device_manifest.xml \
    oplus_radio_device_manifest.xml \
    autobt \
    bip \
    ccci_fsd \
    ccci_mdinit \
    ccci_rpcd \
    charon \
    em_hidl \
    epdg_wod \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss@2.1-service-mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.0-service.trustonic \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron \
    android.hardware.secure_element@1.2-service-mediatek \
    camerahalserver \
    mtkfusionrild \
    vendor.mediatek.hardware.dfps@1.0-service \
    vendor.mediatek.hardware.gpu@1.0-service \
    vendor.mediatek.hardware.keyinstall@1.0-service \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mms@1.5-service \
    vendor.mediatek.hardware.mtkcodecservice@1.1-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    ipsec_mon \
    jpegtool \
    lbs_hidl_service \
    mcDriverDaemon \
    md_monitor \
    md_monitor_ctrl \
    mnld \
    mtk_agpsd \
    netdagent \
    netdc \
    nvram_daemon \
    ppl_agent \
    starter \
    stp_dump3 \
    stroke \
    thermal \
    thermal_manager \
    thermalloadalgod \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua \
    vpud \
    wfca \
    wmt_launcher \
    wmt_loader \
    xcap \
    vtservice \
    vendor.oplus.hardware.biometrics.fingerprint@2.1-service

PRODUCT_PACKAGES += \
    vendor_lib64_hw_vulkan_mt6785_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_mt6785_so \
    vendor_lib64_hw_gatekeeper_default_so
